# === General Settings

#time_zone = "Asia/Tokyo"
#debug = true

[log]
debug   = true
console = true
file    = true
# file_path = /path/to/log

[worker]
interval_minutes = 1
# Avoid to make larger than interval_minutes
minimum_interval_seconds = 30

[schedule]
update_interval_seconds = 120

[datasource.module]
job = "Teng"

[datasource.connector]
dsn = "dbi:mysql:database=koyomi;host=127.0.0.1;port=3306"
user = "root"
password = ""

#[datasource.connector.job]

# === Debug Parameters

[debug]
#now = "2015-05-23T00:00"

[debug.worker]
sleep_seconds = 5
