[log]
debug   = true
console = true
file    = true
# file_path = /path/to/log

[worker]
sleep_seconds = 5

[datasource.module]
job = "Teng"

[datasource.connector]
dsn = "dbi:mysql:database=koyomi;host=127.0.0.1;port=3306"
user = "root"
password = ""

#[datasource.connector.job]
